Bookshop/web/Pages/Cookie.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net;

namespace web.Pages
{
    public class CookieModel : PageModel
    {
        [BindProperty]
        public string ThemeColor { get; set; }
        public IActionResult OnPostSetMode(string value)
        {
            var cookieOptions = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(30)
            };
            if (ThemeColor == "light")
            {
                Response.Cookies.Append("ColorThemeCookie", "dark", cookieOptions);

            }
            else if (ThemeColor == "dark")
            {
                Response.Cookies.Append("ColorThemeCookie", "light", cookieOptions);
            }

            return RedirectToPage("/Index");
        }

    }
}

Bookshop/web/Pages/Search.cshtml.cs
using BLL;
using Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace web.Pages
{
    public class SearchModel : PageModel
    {
        private readonly BookManager bookManager;
        public string Search { get; set; } = string.Empty;

        [BindProperty(SupportsGet = true)]
        public List<Book> Books { get; set; } = new List<Book>();
        public SearchModel(BookManager bookMan)
        {
            bookManager = bookMan;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPostSearch(string search)
        {

            if (search == null)
            {
                Search = string.Empty;
                return Page();
            }
            else
            {
                Search = $"'{search}'";
                Books = bookManager.SearchForBooks(search, bookManager.GetAllBooks());
                return Page();
            }

        }
    }
}

Bookshop/web/Pages/Shared/_Layout.cshtml
@inject IHttpContextAccessor httpContextaccessor
@{
    string theme = Convert.ToString(Html.Raw(httpContextaccessor.HttpContext.Request.Cookies["ColorThemeCookie"]));
    string oppositeTheme = theme == "dark" ? "light" : "dark";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @if (Context.Request.Cookies.ContainsKey("ColorThemeCookie"))
    {
        if (theme.ToString() == "dark")
        {
            <link rel="stylesheet" href="~/css/darkMode.css" asp-append-version="true" />
        }
        else if (theme.ToString() == "light")
        {
            <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        }
        else
        {
            <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        }
    }
    else
    {
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    }

    @*  <link rel="stylesheet" href="~/web.styles.css" asp-append-version="true" />  *@
</head>
<body>
    <header class="">
        <nav id="head" class="navbar navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3">
            <div class="container ">
                <a class="navbar-brand" asp-area="" asp-page="/Index">B&R</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (User.Identity != null && User.Identity.IsAuthenticated)
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-@oppositeTheme" asp-area="" asp-page="/AllBooks">All books</a>
                            </li>
                            <li class="nav-item text-@oppositeTheme">
                                <a class="nav-link text-@oppositeTheme" asp-area="" asp-page="/Library">My library</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-@oppositeTheme" asp-area="" asp-page="/Profile">Profile</a>
                            </li>
                            <!-- Search Bar -->
                            <li class="nav-item d-flex justify-content-center flex-grow-1">
                                <form method="post" asp-page-handler="Search" asp-page="/Search">
                                    <div class="input-group">
                                        <input type="search" class="form-control rounded" name="search" placeholder="Book, author..." aria-label="Search" aria-describedby="search-addon" />
                                        <button type="submit" class="btn btn-light">search</button>
                                    </div>
                                </form>
                            </li>
                            
                            @if (User.HasClaim("UserType", "PowerUser"))
                            {
                                <li class="nav-item d-flex justify-content-end flex-grow-1">
                                    <a class="nav-link text-@oppositeTheme" asp-page="/Contribute">Contribute</a>
                                </li>
                            }
                            <!-- Logout Button -->
                            <li class="nav-item d-flex justify-content-end flex-grow-1">
                                <a class="btn btn-light nav-link text-dark" asp-page="Account/Logout">Logout</a>
                            </li>
                        </ul>
                    </div>
                }
                else
                {
                    <div class="navbar-collapse collapse d-flex flex-row bd-highlight mb-3 justify-content-end">
                        <ul class="navbar-nav">
                            <li class="nav-item ">
                                <a class="nav-link text-@oppositeTheme" asp-area="" asp-page="/Account/Register">Register</a>
                            </li>
                            <li class="nav-item d-flex flex-grow-1">
                                <a class="nav-link text-@oppositeTheme" asp-area="" asp-page="/Account/Login">Login</a>
                            </li>
                        </ul>
                    </div>
                }

            </div>
            <div class="nav-item  justify-content-end" style="display:flex">
                <form method="post" asp-page="/Cookie" asp-page-handler="SetMode">
                    <input type="hidden" value="@theme" name="ThemeColor" />
                    <button type="submit" class="btn btn-@theme border-1 border-@theme">@theme</button>
                </form>
            </div>

        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Bookshop/web/Pages/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Admin Panel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/webapp.styles.css" asp-append-version="true" />
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous" />
    <style>
        #footer {
            padding: 20px;
            font-size: 14px;
            background-color: #333;
            color: #fff;
            position: absolute;
            bottom: 0;
            width: 100%;
        }
    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5/5vz3hFqHW2j5R4CFGm4xDD21RtQD0h0md1b2g" crossorigin="anonymous">
</head>
<body>
    <header style="box-shadow: 0 -6px 10px 5px rgba(0,0,0,0.5); border-color: #212529;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-dark box-shadow mb-3">
           <h1 class="text-white">Admin Panel</h1>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <form method="get" action="/Account/Logout" class="form-inline">
                        <button type="submit" class="btn btn-link nav-link">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <body style="background-color: #212529; color: #fff">
                @RenderBody()
            </body>
        </main>
    </div>

    <footer class="text-center text-white fixed-bottom bg-dark">
        <!-- Grid container -->
        <div class="container p-1 "></div>
        <!-- Grid container -->
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2023 Copyright:
            <a class="text-white" href="https://fontys.nl/">PixelPerfectMedia</a>
        </div>
        <!-- Copyright -->
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5/5vz3hFqHW2j5R4CFGm4xDD21RtQD0h0md1b2g" crossorigin="anonymous"></script>

</body>
</html>