Bookshop/web/Pages/AdminPanel.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace web.Pages
{
    [Authorize(Policy = "PowerUser")]
    public class AdminPanelModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Bookshop/web/Pages/AllBooks.cshtml.cs
using BLL;
using BLL.StrategyFilters;
using Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace web.Pages
{
    public class AllBooksModel : PageModel
    {
        private readonly BookManager bookManager;
        public List<Author> AllAuthors { get; set; }
        public List<Book> Books { get; set; }
        [BindProperty]
        public string Booktype { get; set; }
        [BindProperty]
        public int? SelectedAuthorId { get; set; }
        public AllBooksModel(BookManager bookMan)
        {
            bookManager = bookMan;
        }
        public IActionResult OnGet(int? SelectedAuthorId, string Booktype)
        {
            AllAuthors = bookManager.GetAllAuthors();
            Books = bookManager.GetAllBooks();
            List<IBookFilterStrategy> strategies = new List<IBookFilterStrategy>();

            var authorIds = new List<int>();
            if (SelectedAuthorId != null)
            {
                Author selectedAuthor = AllAuthors.FirstOrDefault(x => x.Id == SelectedAuthorId);
                AuthorFilterStrategy authorFilter = new AuthorFilterStrategy(selectedAuthor);

                strategies.Add(authorFilter);
            }

            // Use trim to remove leading and trailing whitespace
            if (!string.IsNullOrEmpty(Booktype))
            {
                var cleanedBooktype = Booktype.Trim();
                if (cleanedBooktype.Equals("Paperbook", StringComparison.OrdinalIgnoreCase))
                {
                    PaperBookFilterStrategy paperBookFilter = new PaperBookFilterStrategy();
                    strategies.Add(paperBookFilter);
                }
                else if (cleanedBooktype.Equals("Ebook", StringComparison.OrdinalIgnoreCase))
                {
                    EbookFilterStrategy ebookFilter = new EbookFilterStrategy();
                    strategies.Add(ebookFilter);
                }
            }

            Books = bookManager.FilterByStrategies(strategies).ToList();
            return Page();
        }


    }
}

Bookshop/web/Pages/Book.cshtml.cs
using BLL;
using Classes;
using DAL;
using DAL.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.IdentityModel.Tokens;
using Microsoft.Win32;
using System.Net;
using System.Security.Claims;

namespace web.Pages
{
    public class BookModel : PageModel
    {

        private BookManager _bookManager;
        private UserController userController;
        private ReviewManager _reviewManager;

        public List<Review> Reviews { get; set; }
        public int TotalPages { get; set; }
        public int CurrentPage { get; set; }

        public Book Book { get; set; }
        [BindProperty]
        public Review NewReview { get; set; }
        [BindProperty(SupportsGet = true)]
        public Statistics Statistics { get; set; }
        public bool UserHasReviews { get; set; }
        public User MyUser { get; set; }
        public BookModel(BookManager bookManager, ReviewManager reviewMan, UserController userCon)
        {
            userController = userCon;
            _bookManager = bookManager;
            _reviewManager = reviewMan;
            NewReview = new Review();
        }
        [BindProperty]
        public bool pagiButtonPressed { get; set; } = false;
        public IActionResult OnGet(int id, int? pageNumber)
        {
            if (pageNumber != null) { pagiButtonPressed = true; }

            try
            {
                const int pageSize = 5;
                CurrentPage = pageNumber ?? 1;

                int totalReviewCount = _reviewManager.GetTotalReviewCountForBook(id);

                TotalPages = (int)Math.Ceiling(totalReviewCount / (double)pageSize);
                Book = _bookManager.GetBook(id);

                Reviews = _reviewManager.GetReviewsPagination(Book, CurrentPage, pageSize);
                Statistics = _bookManager.GetBookStatistics(Book);

                if (User.Identity != null && User.Identity.IsAuthenticated)
                {
                    int userId = Convert.ToInt32(User.FindFirstValue("id"));
                    MyUser = userController.GetUserLikes(userController.GetUserById(userId));
                    UserHasReviews = _reviewManager.UserHasReviewsOnBook(userId, Book.Id);
                    NewReview = _reviewManager.GetReviewOnBookByUser(MyUser, Book);
                    if (UserHasReviews)
                    {
                        Reviews.Remove(Reviews.FirstOrDefault(x => x.Id == NewReview.Id));
                    }
                }
                return Page();
            }
            catch (Exception x)
            {
                TempData["error"] = x.Message;
                return RedirectToPage("/error");
            }
        }
        public IActionResult OnPost(int bookId)
        {
            if (User.FindFirstValue("id").IsNullOrEmpty())
            {
                @TempData["isLogged"] = "If you want to leave a review, log in first. Don't have an account - register.";
                return RedirectToPage("/Account/Login");
            }

            NewReview.User = userController.GetUserById(Convert.ToInt32(User.FindFirstValue("id")));
            var book = _bookManager.GetBook(bookId);
            var review = new Review(0, NewReview.Comment, NewReview.Rating, DateTime.Now, 0, NewReview.User, book);
            _reviewManager.AddReview(review);
            return RedirectToPage("/Book", new { id = bookId });
        }
        public IActionResult OnPostUserOperations()
        {
            if (User.FindFirstValue("id").IsNullOrEmpty())
            {
                @TempData["isLogged"] = "You need to be logged in for this operation.";
                return RedirectToPage("Account/Login");
            }
            return RedirectToPage("Library");
        }

        public IActionResult OnPostUpvote(int revId)
        {
            if (User.Identity != null && User.Identity.IsAuthenticated)
            {
                var rev = _reviewManager.GetReview(revId);
                User currentUser = userController.GetUserLikes(userController.GetUserById(Convert.ToInt32(User.FindFirstValue("id"))));
                _reviewManager.VoteOnReview(rev, currentUser, "upVote");
                return RedirectToPage("/Book", new { id = rev.Book.Id });
            }
            return RedirectToPage("Login");
        }
        public IActionResult OnPostDownvote(int revId)
        {
            if (User.Identity != null && User.Identity.IsAuthenticated)
            {
                var rev = _reviewManager.GetReview(revId);
                User currentUser = userController.GetUserLikes(userController.GetUserById(Convert.ToInt32(User.FindFirstValue("id"))));
                _reviewManager.VoteOnReview(rev, currentUser, "downVote");
                return RedirectToPage("/Book", new { id = rev.Book.Id });
            }
            return RedirectToPage("Login");
        }
        public IActionResult OnPostEdit(int revId)
        {
            HttpContext.Session.SetInt32("reviewId", revId);
            return RedirectToPage("/Edit");
        }
    }
}

Bookshop/web/Pages/Contribute.cshtml.cs
using BLL;
using Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace web.Pages
{
    [BindProperties(SupportsGet = true)]
    public class ContributeModel : PageModel
    {
        private readonly BookManager _bookManager;

        public Book Book { get; set; }

        public int Pages { get; set; }
        public List<Author> AllAuthors { get; set; } // Populate this list with available authors

        public List<int> SelectedAuthors { get; set; } // Holds the selected author IDs
        public string ISBN { get; set; }
        public string ISBN10 { get; set; }
        public double Filesize { get; set; }
        public string DownloadLink { get; set; }

        public ContributeModel(BookManager bookManager)
        {
            _bookManager = bookManager;
        }
        public void OnGet()
        {
            AllAuthors = _bookManager.GetAllAuthors();
        }

        public IActionResult OnPostBook()
        {
          
            var errorMessages = new List<string>();
            try
            {
                var paperBook = new PaperBook(Book.Id, Book.Title, Book.Description, Book.Publisher, Book.Language,
                 Book.PublicationDate, Book.Format, GetAuthorsByIds(SelectedAuthors), Pages, ISBN, ISBN10);

                _bookManager.AddNewBook(paperBook);

            }
            catch (Exception arg)
            {
                errorMessages.Add(arg.Message);
            }
            if (errorMessages.Count > 0)
            {
                string errorMessage = string.Join(Environment.NewLine, errorMessages);
                AllAuthors = _bookManager.GetAllAuthors();
                TempData["errors"] = errorMessage;
                return Page();
            }
            TempData["Message"] = "Thank you for your contribution! Your book will be reviewed by our team.";
            return RedirectToPage("/Index");
        }
        public IActionResult OnPostEBook()
        {
            var errorMessages = new List<string>();
            try
            {
                var ebook = new EBook(Book.Id, Book.Title, Book.Description, Book.Publisher, Book.Language,
               Book.PublicationDate, Book.Format, GetAuthorsByIds(SelectedAuthors), Filesize, DownloadLink);

                _bookManager.AddNewBook(ebook);

            }
            catch (Exception arg)
            {
                errorMessages.Add(arg.Message);
            }
            if (errorMessages.Count > 0)
            {
                string errorMessage = string.Join(Environment.NewLine, errorMessages);
                AllAuthors = _bookManager.GetAllAuthors();
                TempData["errors"] = errorMessage;
                return Page();
            }
            TempData["Message"] = "Thank you for your contribution! Your book will be reviewed by our team.";
            return RedirectToPage("/Index");
        }

        private List<Author> GetAuthorsByIds(List<int> authorIds)
        {
            var authors = _bookManager.GetAllAuthors();
            foreach (var author in authors)
            {
                if (authorIds.Contains(author.Id))
                {
                    return new List<Author> { author };
                }
            }

            return new List<Author>();
        }
    }
}

Bookshop/web/Pages/Cookie.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net;

namespace web.Pages
{
    public class CookieModel : PageModel
    {
        [BindProperty]
        public string ThemeColor { get; set; }
        public IActionResult OnPostSetMode(string value)
        {
            var cookieOptions = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(30)
            };
            if (ThemeColor == "light")
            {
                Response.Cookies.Append("ColorThemeCookie", "dark", cookieOptions);

            }
            else if (ThemeColor == "dark")
            {
                Response.Cookies.Append("ColorThemeCookie", "light", cookieOptions);
            }

            return RedirectToPage("/Index");
        }

    }
}

Bookshop/web/Pages/Edit.cshtml.cs
using BLL;
using Classes;
using DAL;
using DAL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace web.Pages
{
    [BindProperties]
    public class EditModel : PageModel
    {
        private BookManager _bookMan;
        private BLL.ReviewManager _reviewManager;
        public EditModel(IBookRepository Brepo, IReviewRepository Rrepo, BLL.ReviewManager reviewManager)
        {
            _bookMan = new BookManager(Brepo, Rrepo);
            _reviewManager =  reviewManager;
        }
        public Review SelectedReview { get; set; }
        public IActionResult OnGet()
        {
            if (User.Identity != null && User.Identity.IsAuthenticated)
            {
                int reviewId = Convert.ToInt32(HttpContext.Session.GetInt32("reviewId"));
                SelectedReview = _reviewManager.GetReview(reviewId);
                return Page();
            }
            TempData["isLogged"] = "You do not have permission for that operation.";
            return RedirectToPage("/Login");
        }
        public IActionResult OnPost()
        {
            SelectedReview.Id = Convert.ToInt32(HttpContext.Session.GetInt32("reviewId"));
            _reviewManager.UpdateReview(SelectedReview);
            HttpContext.Session.Remove("reviewId");
            return RedirectToPage("/Profile");
        }
        public IActionResult OnPostDelete()
        {
            SelectedReview.Id = Convert.ToInt32(HttpContext.Session.GetInt32("reviewId"));
            _reviewManager.DeleteReview(SelectedReview);
            HttpContext.Session.Remove("reviewId");
            return RedirectToPage("/Profile");
        }
    }
}

Bookshop/web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Bookshop/web/Pages/Index.cshtml.cs
using BLL;
using Classes;
using DAL;
using DAL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics.Eventing.Reader;
using System.Net;

namespace web.Pages
{
    public class IndexModel : PageModel
    {
        private BookManager bookManager;

        public Dictionary<Book, Statistics> TopBooks { get; set; }


        public IndexModel(IBookRepository bookRepo, IReviewRepository reviewRepo)
        {
            bookManager = new BookManager(bookRepo, reviewRepo);
        }

        public void OnGet()
        {
            TopBooks = bookManager.SortBooksByRating(bookManager.GetAllBooks()).Take(12).ToDictionary(pair => pair.Key, pair => pair.Value); ;
        }
        public IActionResult OnPost(int? id)
        {
            return RedirectToPage("/Book", id);
        }

    }
}

Bookshop/web/Pages/Library.cshtml.cs
using BLL;
using Classes;
using DAL.Interfaces;
using DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace web.Pages
{
    public class LibraryModel : PageModel
    {
        private UserController _userCon;
        private BookManager _bookManager;
        private BLL.ReviewManager _reviewManager;

        public List<Book> recommendedBooks { get; set; }
        public LibraryModel(IReviewRepository reviewRepository, IUserRepository userRepository, IBookRepository bookRepo, ReviewManager revMan)
        {
            _reviewManager = revMan;
            _userCon = new UserController(userRepository);
            _bookManager = new BookManager(bookRepo, reviewRepository);
        }
        public void OnGet()
        {
            //Recommended
            Dictionary<Book, List<Review>> books = new Dictionary<Book, List<Review>>();
            Dictionary<User, List<Review>> users = new Dictionary<User, List<Review>>();
            
            var allUsers = _userCon.GetAllUsers();
            var allBooks = _bookManager.GetAllBooks();
            foreach (var book in allBooks)
            {
                var reviews = _reviewManager.GetAllReviewsByBook(book);
                books.Add(book, reviews);
            }
            foreach (var user in allUsers)
            {
                var reviews = _reviewManager.GetAllReviewsByUser(user);
                users.Add(user, reviews);
            }
            RecommendationEngine engine = new RecommendationEngine(books, users);
            //try
            //{
            recommendedBooks = engine.GetRecommendations(Convert.ToInt32(User.FindFirstValue("id")));
            //}
            //catch (Exception ex)
            //{
            //    TempData["recommendationErrors"] = ex.Message;
            //}



        }
    }
}

Bookshop/web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Bookshop/web/Pages/AdminPanel.cshtml
@page
@model web.Pages.AdminPanelModel
@{
    Layout = "Shared/_LayoutAdmin";
}

Bookshop/web/Pages/Book.cshtml
@page
@using Classes;
@model web.Pages.BookModel
@{
}
@inject BLL.BookManager bookManager;
<div class="container">
    <div class="row">
        <div class="col-3">
            <div class="row">
                <img src="~/book.png" />
            </div>
            <div class="row mt-2 text-center">
                <div class="col">
                    <form method="post" asp-page-handler="OnPostUserOperations">
                        <input type="hidden" />
                        <button type="submit" class="btn btn-secondary border border-1 border-success rounded-pill" asp-page-handler="UserOperations"> Want to read</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="row">
                @if (Model.Book.GetType() == typeof(PaperBook))
                {
                    var paperBook = (PaperBook)Model.Book;
                    <h1> @paperBook.Title</h1>
                    <h3> @string.Join(',',paperBook.Authors.Select(author => author.FullName))</h3>
                    <p>@paperBook.Description</p>
                    <h4>Publication year: @paperBook.PublicationDate</h4>
                    <h4>Publisher: @paperBook.Publisher</h4>
                    <h4>ISBN: @paperBook.ISBN</h4>
                    <h4>ISBN10: @paperBook.ISBN10</h4>
                }
                else if (Model.Book.GetType() == typeof(EBook))
                {
                    var ebook = (EBook)Model.Book;
                    <h1> @ebook.Title</h1>
                    <h3>@string.Join(',',ebook.Authors.Select(author => author.FullName))</h3>
                    <p>@ebook.Description</p>
                    <h4>Publication year: @ebook.PublicationDate</h4>
                    <h4>Publisher: @ebook.Publisher</h4>
                    <h4>Format: @ebook.Format</h4>
                    <h4>File size: @ebook.FileSize</h4>
                }
                <hr />
            </div>
            <h2>Rating</h2>
            <div class="row">
                <div class="col-10">
                    <div class="row">
                        <div class="col-2">
                            <h5>5 stars</h5>
                        </div>
                        <div class="col-8 mt-1">
                            <div class="progress rounded-pill">
                                <div class="progress-bar rounded-pill bg-warning " role="progressbar" style="width: @Model.Statistics.fiveStarReviewsPercentage%" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                        <div class="col-2">
                            <p class="text-secondary">@Model.Statistics.fiveStarReviewsCount (@Model.Statistics.fiveStarReviewsPercentage<span>%</span>)</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-2">
                            <h5>4 stars</h5>
                        </div>
                        <div class="col-8 mt-1">
                            <div class="progress rounded-pill">
                                <div class="progress-bar rounded-pill bg-warning " role="progressbar" style="width: @Model.Statistics.fourStarReviewsPercentage%" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                        <div class="col-2">
                            <p class="text-secondary">@Model.Statistics.fourStarReviewsCount (@Model.Statistics.fourStarReviewsPercentage<span>%</span>)</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-2">
                            <h5>3 stars</h5>
                        </div>
                        <div class="col-8 mt-1">
                            <div class="progress rounded-pill">
                                <div class="progress-bar rounded-pill bg-warning " role="progressbar" style="width: @Model.Statistics.threeStarReviewsPercentage%" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                        <div class="col-2">
                            <p class="text-secondary">@Model.Statistics.threeStarReviewsCount (@Model.Statistics.threeStarReviewsPercentage<span>%</span>)</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-2">
                            <h5>2 stars</h5>
                        </div>
                        <div class="col-8 mt-1">
                            <div class="progress rounded-pill">
                                <div class="progress-bar rounded-pill bg-warning " role="progressbar" style="width: @Model.Statistics.twoStarReviewsPercentage%" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                        <div class="col-2">
                            <p class="text-secondary">@Model.Statistics.twoStarReviewsCount (@Model.Statistics.twoStarReviewsPercentage<span>%</span>)</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-2">
                            <h5>1 stars</h5>
                        </div>
                        <div class="col-8 mt-1">
                            <div class="progress rounded-pill">
                                <div class="progress-bar rounded-pill bg-warning " role="progressbar" style="width: @Model.Statistics.oneStarReviewsPercentage%" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                        <div class="col-2">
                            <p class="text-secondary">@Model.Statistics.oneStarReviewsCount (@Model.Statistics.oneStarReviewsPercentage<span>%</span>)</p>
                        </div>
                    </div>
                </div>
                <div class="col-2 text-center mt-5">
                    <div class="row">
                        <h4> @Model.Statistics.Average/5 &#11088;</h4>
                    </div>
                    <div class="row">
                        <p class="text-secondary">@Model.Statistics.ReviewCount reviews</p>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>
<hr />

<div class="container mt-3">
    <h2>Ratings & Reviews</h2>
    @if (Model.UserHasReviews)
    {
        <div class="text-center">
            @if (Model.NewReview.User.PicturePath != "noPic")
            {
                <img id="userIcon" style="border-radius:70%; width:5%; height:5%;" src="~/uploads/@Model.NewReview.User.PicturePath">
            }
            else
            {
                <img id="userIcon" style="border-radius:70%; width:5%; height:5%;" src="~/userIcon.png">
            }
            <h1 class="">Your review</h1>
            @for (int i = 0; i < Model.NewReview.Rating; i++)
            {
                <span>&#11088</span>
            }
            <p class="mt-2 border border-dark border-3 rounded-3">@Model.NewReview.Date | <span class="bg-black text-white"> @Model.NewReview.Likes👍</span></p>
            <p class="">@Model.NewReview.Comment</p>
            <form method="post" asp-page-handler="Edit">
                <input type="hidden" value="@Model.NewReview.Id" name="revId" />
                <button type="submit">Edit</button>
            </form>

        </div>
    }
    else
    {
        <div class="text-center">
            <img id="userIcon" style="border-radius:70%; width:5%; height:5%;" src="~/userIcon.png">
            <h1 class="">What do you think?</h1>
        </div>
        <form method="post" asp-page-handler="OnPost">
            <div class="form-group">
                <label for="comment">Comment:</label>
                <textarea asp-for="NewReview.Comment" class="form-control" id="reviewForm" name="Comment" rows="4" required></textarea>
            </div>
            <div class="form-group">
                <label for="rating">Rating:</label>
                <select asp-for="NewReview.Rating" class="form-control" id="reviewForm" name="Rating" required>
                    <option value="1">1 - Poor</option>
                    <option value="2">2 - Fair</option>
                    <option value="3">3 - Good</option>
                    <option value="4">4 - Very Good</option>
                    <option value="5">5 - Excellent</option>
                </select>
            </div>

            <div class="form-group">
                <input type="hidden" value="@Model.Book.Id" name="bookId" />
                <button type="submit" class="btn btn-primary" asp-page-handler="OnPost">Submit Review</button>
            </div>
        </form>
    }

    <hr />
</div>

<div id="scroll-pagi" class="container">
    <div class=" row text-center">
        <h3>Community Reviews</h3>
    </div>
    @foreach (var review in Model.Reviews)
    {

        <div class="row">
            <div class="col-3">
            </div>
            <div class="col-9">
                <div class="row">
                    <div class="col-4">
                        <div style="width: 40px; height: 40px; overflow: hidden; border-radius: 50%;">
                            <img id="userIcon" style="width: 100%; height: 100%;" src="~/uploads/@review.User.PicturePath" alt="User Icon">
                        </div>
                        <h5>@review.User.Name</h5>
                        <p class="text-light">@review.User.Username</p>

                    </div>
                    <div class="col-8">
                        <div class="row">
                            <div class="col text-start">
                                @for (int i = 0; i < review.Rating; i++)
                                {
                                    <span>&#11088</span>
                                }
                                <p class="">@review.Date</p>
                            </div>
                            @if (Model.MyUser != null)
                            {
                                <div class="col text-end">
                                    <form method="post" asp-page-handler="Upvote">
                                        <span class=" text-muted">@review.Likes likes </span>
                                        <input type="hidden" value="@review.Id" name="revId" />
                                        <input type="hidden" value="@Model.Book.Id" name="bookId" />
                                        <button type="submit" id="upvoteArrow" class="btn" style="background-color:@(Model.MyUser.LikedReviews.ContainsKey(review.Id) ? "green" : null)" @if (Model.MyUser.LikedReviews.ContainsKey(review.Id))
                                        {
                                            <text>disabled</text>
                                        }><span>↑</span></button>
                                    </form>

                                    <form method="post" asp-page-handler="Downvote">
                                        <input type="hidden" value="@review.Id" name="revId" />
                                        <input type="hidden" value="@Model.Book.Id" name="bookId" />
                                        <button type="submit" id="downvoteArrow" class="btn" style="background-color:@(Model.MyUser.DislikedReviews.ContainsKey(review.Id) ? "red" : null)" @if (Model.MyUser.DislikedReviews.ContainsKey(review.Id))
                                        {
                                            <text>disabled</text>
                                        }><span>↓</span></button>
                                    </form>
                                    <form method="post" asp-page-handler="DownVote">
                                    </form>
                                </div>
                            }
                            
                        </div>
                        <div class="row ">
                            <div class="col">
                                <p>@review.Comment</p>
                            </div>
                        </div>

                    </div>
                </div>
                <hr>
            </div>
        </div>
    }
</div>
<div class="row text-center">
    <div class="col">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                @for (int i = 1; i <= Model.TotalPages; i++)
                {
                    <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                        <a class="page-link" asp-page="Book" asp-route-id="@Model.Book.Id" asp-route-pageNumber="@i" ('@i')">@i</a>
                    </li>
                }
            </ul>
        </nav>
    </div>
</div>
@if (Model.pagiButtonPressed)
{
    <script>
        var searchResultsSection = document.getElementById("scroll-pagi");  // Replace "search-results" with the actual ID or selector of your search results section
        if (searchResultsSection) {
            searchResultsSection.scrollIntoView({ behavior: "smooth" });
        }
    </script>
}

Bookshop/web/Pages/Cookie.cshtml
@page
@model web.Pages.CookieModel
@{
}

Bookshop/web/Pages/Library.cshtml
@page
@model web.Pages.LibraryModel
@{
}
<h1>Recommended</h1>

@if (TempData["recommendationErrors"] == null)
{
    <div class="list-group">
        @foreach (var book in Model.recommendedBooks)
        {
            <a href="/Book/?id=@book.Id" class="list-group-item list-group-item-action"> <h6>@book.Title</h6></a>
        }
    </div>
}
else
{
    <h3>@TempData["recommendationErrors"]</h3>
}

<hr />